name: Integrations

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:

  FeatureFlags:
    
    runs-on: self-hosted
    environment: home
    
    steps:

      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Only Run - TESTING
        run: |
          echo "TESTING FEATURE FLAG ENABLED"
        if: ${{ vars.HOMECI_FEATURE_TESTING }}

  Connectivity:
    
    runs-on: self-hosted
    environment: home
    
    steps:

      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Login to Infisical
        uses: Infisical/secrets-action@v1.0.9
        with:
          method: universal
          client-id: ${{ secrets.INFISICAL_UNIVERSAL_AUTH_CLIENT_ID }}
          client-secret: ${{ secrets.INFISICAL_UNIVERSAL_AUTH_CLIENT_SECRET }}
          domain: ${{ vars.INFISICAL_DOMAIN }}
          env-slug: ${{ vars.INFISICAL_ENV_SLUG }}
          project-slug: ${{ vars.INFISICAL_PROJECT_SLUG }}
          secret-path: /export/github/test

      - name: Setup Docker Compose
        uses: docker/setup-compose-action@v1

      - name: Testing
        run: |
          docker ps
        env:
          DOCKER_HOST: tcp://${{ vars.DOCKER_HOST_MANAGER }}

