name: Tailscale Connectivity

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:

  TailscaleTest:
    
    runs-on: ubuntu-latest
    environment: home
    
    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Connect to Tailscale
        uses: ./.github/actions/tailscale
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-client-secret: ${{ secrets.TS_OAUTH_CLIENT_SECRET }}
          tags: ${{ vars.TS_TAGS }}
          use-cache: true

      - name: Test Tailscale Connection
        run: |
          tailscale status
          tailscale ip -4
          
      - name: Test Target Network Connection
        run: |
          ping -c 1 ${{ vars.TS_PING_IP }} 
