name: Tailscale Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:

  Test:
    
    runs-on: ubuntu-latest
    environment: home
    
    steps:

      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Connect to Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: ${{ vars.TS_TAGS }} 

      - name: Test Tailscale connection
        run: |
          tailscale status
          tailscale ip -4
          
      - name: Your application logic here
        run: |
          ping -c 1 10.1.1.1
          ping -c 1 10.1.1.2
